import { desc, eq, sql } from "drizzle-orm";
import { z } from "zod";
import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { protectedProcedure, roleProcedure, router, publicProcedure } from "./_core/trpc";
import { createLocalUser, getDb, getUserByUsername } from "./db";
import { auditLogs, checklistRuns, clients, communications, inventoryItems, inventoryMovements, materialRequests, postSales, productionOrders, projectCosts, projects, proposalItems, proposals, suppliers } from "../drizzle/schema";
import { createSessionToken } from "./_core/auth";
import { compare, hash } from "bcryptjs";

const clientInput = z.object({ name: z.string().min(2), company: z.string().optional(), email: z.string().email().optional().or(z.literal("")), phone: z.string().optional(), segment: z.string().optional() });
const proposalInput = z.object({ clientId: z.number().int().positive(), title: z.string().min(2), totalValue: z.number().nonnegative(), conditions: z.string().optional() });
const projectInput = z.object({ clientId: z.number().int().positive(), proposalId: z.number().int().positive().optional(), name: z.string().min(2), soldValue: z.number().nonnegative(), plannedCost: z.number().nonnegative(), dueDate: z.date().optional() });
const orderInput = z.object({ projectId: z.number().int().positive(), title: z.string().min(2), priority: z.enum(["low", "medium", "high", "critical"]).default("medium"), dueDate: z.date().optional() });
const stockInput = z.object({ sku: z.string().min(1), name: z.string().min(2), category: z.string().optional(), quantity: z.number().nonnegative(), minimumQuantity: z.number().nonnegative(), averageCost: z.number().nonnegative() });
const supplierInput = z.object({ name: z.string().min(2), category: z.string().optional(), contactName: z.string().optional(), email: z.string().email().optional().or(z.literal("")), phone: z.string().optional(), paymentTerms: z.string().optional() });
const costInput = z.object({ projectId: z.number().int().positive(), category: z.enum(["material", "service", "expense"]), description: z.string().min(2), plannedValue: z.number().nonnegative(), actualValue: z.number().nonnegative() });

export const appRouter = router({
  system: systemRouter,
  auth: router({
    me: publicProcedure.query(opts => opts.ctx.user),
    login: publicProcedure.input(z.object({ username: z.string().min(1), password: z.string().min(1) })).mutation(async ({ input, ctx }) => {
      const user = await getUserByUsername(input.username);
      if (!user || !user.passwordHash) {
        throw new Error("Usuário ou senha inválidos.");
      }
      const valid = await compare(input.password, user.passwordHash);
      if (!valid) {
        throw new Error("Usuário ou senha inválidos.");
      }
      const token = await createSessionToken(user.id, user.username ?? user.name ?? "", user.role, { expiresInMs: 1000 * 60 * 60 * 24 * 30 });
      const cookieOptions = getSessionCookieOptions(ctx.req);
      ctx.res.cookie(COOKIE_NAME, token, { ...cookieOptions, maxAge: 1000 * 60 * 60 * 24 * 30 });
      return { success: true, user: { id: user.id, name: user.name, role: user.role } };
    }),
    logout: publicProcedure.mutation(({ ctx }) => {
      const cookieOptions = getSessionCookieOptions(ctx.req);
      ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 });
      return { success: true } as const;
    }),
    register: publicProcedure.input(z.object({
      name: z.string().min(2, "Nome deve ter ao menos 2 caracteres"),
      username: z.string().min(3, "Usuário deve ter ao menos 3 caracteres"),
      password: z.string().min(6, "Senha deve ter ao menos 6 caracteres"),
    })).mutation(async ({ input, ctx }) => {
      const existing = await getUserByUsername(input.username);
      if (existing) throw new Error("Esse nome de usuário já está em uso.");
      const passwordHash = await hash(input.password, 10);
      await createLocalUser(input.username, passwordHash, input.name, "user");
      const user = await getUserByUsername(input.username);
      if (!user) throw new Error("Erro ao criar conta. Tente novamente.");
      const token = await createSessionToken(user.id, user.username ?? user.name ?? "", user.role, { expiresInMs: 1000 * 60 * 60 * 24 * 30 });
      const cookieOptions = getSessionCookieOptions(ctx.req);
      ctx.res.cookie(COOKIE_NAME, token, { ...cookieOptions, maxAge: 1000 * 60 * 60 * 24 * 30 });
      return { success: true, user: { id: user.id, name: user.name, role: user.role } };
    }),
  }),
  dashboard: router({
    summary: protectedProcedure.query(async () => { const db = await getDb(); if (!db) return { projects: 0, proposals: 0, orders: 0, clients: 0, stockAlerts: 0, overdueOrders: 0, budgetAlerts: 0, postSaleToday: 0 }; const [a,b,c,d,e,f,g,h] = await Promise.all([db.select({ count: sql<number>`count(*)` }).from(projects), db.select({ count: sql<number>`count(*)` }).from(proposals), db.select({ count: sql<number>`count(*)` }).from(productionOrders), db.select({ count: sql<number>`count(*)` }).from(clients), db.select({ count: sql<number>`count(*)` }).from(inventoryItems).where(sql`${inventoryItems.quantity} <= ${inventoryItems.minimumQuantity}`), db.select({ count: sql<number>`count(*)` }).from(productionOrders).where(eq(productionOrders.status, "blocked")), db.select({ count: sql<number>`count(*)` }).from(projects).where(sql`${projects.actualCost} > ${projects.plannedCost}`), db.select({ count: sql<number>`count(*)` }).from(postSales).where(eq(postSales.stage, "scheduled"))]); return { projects: Number(a[0]?.count ?? 0), proposals: Number(b[0]?.count ?? 0), orders: Number(c[0]?.count ?? 0), clients: Number(d[0]?.count ?? 0), stockAlerts: Number(e[0]?.count ?? 0), overdueOrders: Number(f[0]?.count ?? 0), budgetAlerts: Number(g[0]?.count ?? 0), postSaleToday: Number(h[0]?.count ?? 0) }; }),
    attention: protectedProcedure.query(async () => { const db = await getDb(); if (!db) return { orders: [], stock: [], suppliers: [], postSale: [] }; const [orders, stock, delayed, postSale] = await Promise.all([db.select().from(productionOrders).where(eq(productionOrders.status, "blocked")).limit(5), db.select().from(inventoryItems).where(sql`${inventoryItems.quantity} <= ${inventoryItems.minimumQuantity}`).limit(5), db.select().from(suppliers).where(eq(suppliers.deliveryStatus, "delayed")).limit(5), db.select().from(postSales).where(eq(postSales.stage, "scheduled")).limit(5)]); return { orders, stock, suppliers: delayed, postSale }; }),
  }),
  clients: router({ list: protectedProcedure.query(async () => { const db = await getDb(); return db ? db.select().from(clients).orderBy(desc(clients.createdAt)).limit(100) : []; }), create: roleProcedure("comercial", "gestor").input(clientInput).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); const result = await db.insert(clients).values(input); await db.insert(auditLogs).values({ userId: ctx.user.id, entity: "client", action: "created", details: input.name }); return result; }), update: roleProcedure("comercial", "gestor").input(z.object({ id: z.number().int().positive(), ...clientInput.shape })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); const { id, ...data } = input; return db.update(clients).set(data).where(eq(clients.id, id)); }) }),
  proposals: router({ list: protectedProcedure.query(async () => { const db = await getDb(); return db ? db.select().from(proposals).orderBy(desc(proposals.updatedAt)).limit(100) : []; }), create: roleProcedure("comercial", "gestor").input(proposalInput).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); const code = `PRP-${Date.now().toString().slice(-6)}`; return db.insert(proposals).values({ ...input, totalValue: input.totalValue.toFixed(2), code }); }), approve: roleProcedure("comercial", "gestor").input(z.object({ id: z.number().int().positive() })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); return db.update(proposals).set({ status: "approved" }).where(eq(proposals.id, input.id)); }), addItem: roleProcedure("comercial", "gestor").input(z.object({ proposalId: z.number().int().positive(), description: z.string().min(2), quantity: z.number().positive(), unitValue: z.number().nonnegative() })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); return db.insert(proposalItems).values({ ...input, quantity: input.quantity.toFixed(2), unitValue: input.unitValue.toFixed(2), totalValue: (input.quantity * input.unitValue).toFixed(2) }); }), convertToProject: roleProcedure("comercial", "gestor").input(z.object({ id: z.number().int().positive(), dueDate: z.date().optional() })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); const found = await db.select().from(proposals).where(eq(proposals.id, input.id)).limit(1); const proposal = found[0]; if (!proposal || proposal.status !== "approved") throw new Error("A proposta precisa estar aprovada antes da conversão."); const code = `PRJ-${Date.now().toString().slice(-6)}`; return db.insert(projects).values({ clientId: proposal.clientId, proposalId: proposal.id, name: proposal.title, code, soldValue: proposal.totalValue, plannedCost: "0", dueDate: input.dueDate }); }) }),
  projects: router({ list: protectedProcedure.query(async () => { const db = await getDb(); return db ? db.select().from(projects).orderBy(desc(projects.updatedAt)).limit(100) : []; }), create: roleProcedure("gestor", "comercial").input(projectInput).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); const code = `PRJ-${Date.now().toString().slice(-6)}`; return db.insert(projects).values({ ...input, code, soldValue: input.soldValue.toFixed(2), plannedCost: input.plannedCost.toFixed(2) }); }), updateStatus: roleProcedure("gestor", "producao").input(z.object({ id: z.number().int().positive(), status: z.enum(["planning", "in_progress", "paused", "delivered", "post_sale"]) })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); return db.update(projects).set({ status: input.status }).where(eq(projects.id, input.id)); }) }),
  production: router({ list: protectedProcedure.query(async () => { const db = await getDb(); return db ? db.select().from(productionOrders).orderBy(desc(productionOrders.updatedAt)).limit(100) : []; }), create: roleProcedure("gestor", "producao").input(orderInput).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); const code = `OP-${Date.now().toString().slice(-6)}`; return db.insert(productionOrders).values({ ...input, code }); }), updateProgress: roleProcedure("gestor", "producao").input(z.object({ id: z.number().int().positive(), progress: z.number().int().min(0).max(100), status: z.enum(["queued", "in_progress", "blocked", "done"]) })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); return db.update(productionOrders).set({ progress: input.progress, status: input.status }).where(eq(productionOrders.id, input.id)); }) }),
  stock: router({ list: protectedProcedure.query(async () => { const db = await getDb(); return db ? db.select().from(inventoryItems).orderBy(desc(inventoryItems.updatedAt)).limit(200) : []; }), create: roleProcedure("compras", "gestor").input(stockInput).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); return db.insert(inventoryItems).values({ ...input, quantity: input.quantity.toFixed(2), minimumQuantity: input.minimumQuantity.toFixed(2), averageCost: input.averageCost.toFixed(2) }); }), movement: roleProcedure("compras", "producao", "gestor").input(z.object({ itemId: z.number().int().positive(), type: z.enum(["in", "out", "reserve", "release"]), quantity: z.number().positive(), note: z.string().optional() })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); return db.insert(inventoryMovements).values({ ...input, quantity: input.quantity.toFixed(2), createdBy: ctx.user.id }); }) }),
  suppliers: router({ list: protectedProcedure.query(async () => { const db = await getDb(); return db ? db.select().from(suppliers).orderBy(desc(suppliers.createdAt)).limit(100) : []; }), create: roleProcedure("compras", "gestor").input(supplierInput).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); return db.insert(suppliers).values(input); }) }),
  costs: router({ list: protectedProcedure.input(z.object({ projectId: z.number().int().positive() })).query(async ({ input }) => { const db = await getDb(); return db ? db.select().from(projectCosts).where(eq(projectCosts.projectId, input.projectId)).orderBy(desc(projectCosts.createdAt)) : []; }), add: roleProcedure("gestor", "compras").input(costInput).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); return db.insert(projectCosts).values({ ...input, plannedValue: input.plannedValue.toFixed(2), actualValue: input.actualValue.toFixed(2) }); }) }),
  postSale: router({ list: protectedProcedure.query(async () => { const db = await getDb(); return db ? db.select().from(postSales).orderBy(desc(postSales.createdAt)).limit(100) : []; }), update: roleProcedure("pos_venda", "gestor").input(z.object({ id: z.number().int().positive(), stage: z.enum(["scheduled", "contacted", "satisfied", "opportunity", "closed"]), satisfactionScore: z.number().int().min(0).max(10).optional(), notes: z.string().optional() })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); return db.update(postSales).set(input).where(eq(postSales.id, input.id)); }) }),
  checklists: router({ list: protectedProcedure.input(z.object({ orderId: z.number().int().positive() })).query(async ({ input }) => { const db = await getDb(); return db ? db.select().from(checklistRuns).where(eq(checklistRuns.orderId, input.orderId)) : []; }), complete: roleProcedure("producao", "gestor").input(z.object({ id: z.number().int().positive(), evidenceUrl: z.string().optional() })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); return db.update(checklistRuns).set({ status: "done", evidenceUrl: input.evidenceUrl, completedBy: ctx.user.id, completedAt: new Date() }).where(eq(checklistRuns.id, input.id)); }) }),
  communications: router({ list: protectedProcedure.query(async () => { const db = await getDb(); return db ? db.select().from(communications).orderBy(desc(communications.scheduledAt)).limit(100) : []; }), schedule: roleProcedure("comercial", "pos_venda", "gestor").input(z.object({ clientId: z.number().int().positive(), projectId: z.number().int().positive().optional(), stage: z.enum(["proposal_sent", "awaiting_response", "production_started", "delivery", "satisfaction", "post_sale"]), subject: z.string().min(2), body: z.string().optional(), scheduledAt: z.date().optional() })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); return db.insert(communications).values(input); }) }),
  materialRequests: router({ list: protectedProcedure.query(async () => { const db = await getDb(); return db ? db.select().from(materialRequests).orderBy(desc(materialRequests.createdAt)).limit(100) : []; }), create: roleProcedure("producao", "compras", "gestor").input(z.object({ description: z.string().min(2), projectId: z.number().int().positive().optional(), orderId: z.number().int().positive().optional(), urgency: z.enum(["normal", "urgent"]).default("normal") })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); return db.insert(materialRequests).values({ ...input, requesterId: ctx.user.id }); }), approve: roleProcedure("compras", "gestor").input(z.object({ id: z.number().int().positive(), status: z.enum(["approved", "rejected", "purchased", "delivered"]) })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Banco indisponível"); return db.update(materialRequests).set({ status: input.status }).where(eq(materialRequests.id, input.id)); }) }),
  reports: router({ overview: protectedProcedure.query(async () => { const db = await getDb(); if (!db) return { sold: 0, planned: 0, actual: 0, margin: 0, suppliersAtRisk: 0 }; const [financials, risk] = await Promise.all([db.select({ sold: sql<number>`coalesce(sum(${projects.soldValue}),0)`, planned: sql<number>`coalesce(sum(${projects.plannedCost}),0)`, actual: sql<number>`coalesce(sum(${projects.actualCost}),0)` }).from(projects), db.select({ count: sql<number>`count(*)` }).from(suppliers).where(eq(suppliers.deliveryStatus, "delayed"))]); const sold = Number(financials[0]?.sold ?? 0); const actual = Number(financials[0]?.actual ?? 0); return { sold, planned: Number(financials[0]?.planned ?? 0), actual, margin: sold ? ((sold - actual) / sold) * 100 : 0, suppliersAtRisk: Number(risk[0]?.count ?? 0) }; }) }),
});

export type AppRouter = typeof appRouter;
